export { default as HeroSection } from './HeroSection'
export { default as RealitySection } from './RealitySection'
export {default as HighlightsSection} from './HighlightsSection'
export {default as WhySPMSection} from './WhySPMSection'
export { default as DeliverablesSection } from './DeliverablesSection'
export { default as WhoIsThisForSection } from './WhoIsThisForSection'
export { default as EventDetailsSection } from './EventDetailsSection'
export { default as CoachSection } from './CoachSection'
export { default as FAQSection } from './FAQSection'
export { default as ContactSection } from './ContactSection'
